//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastAndFinalVersion.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AttendanceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendanceList()
        {
            this.ChildCourses = new ObservableCollection<ChildCourse>();
            this.RegisterStudents = new ObservableCollection<RegisterStudent>();
        }
    
        public int sNr { get; set; }
        public int SN { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public byte[] dateArrival { get; set; }
        public Nullable<System.DateTime> dateDeparture { get; set; }
        public Nullable<int> hoursSpent { get; set; }
    
        public virtual RegisterStudent RegisterStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<ChildCourse> ChildCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<RegisterStudent> RegisterStudents { get; set; }
    }
}
