//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastAndFinalVersion.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ChildCourse
    {
        public int courseID { get; set; }
        public string UserName { get; set; }
        public int sNr { get; set; }
    
        public virtual AttendanceList AttendanceList { get; set; }
    }
}
