//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastAndFinalVersion.Model
{
    using LastAndFinalVersion.Commands;
    using LastAndFinalVersion.ViewModel;
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel;

    public partial class Cours:INotifyPropertyChanged
    {
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.RegisterTeachers = new ObservableCollection<RegisterTeacher>();
           // RegisterTeacherViewModel rt = new RegisterTeacherViewModel();
           
             //   IsChecked = true;
        }
    
        public string courseName { get; set; }
        public int SNTeacher { get; set; }
        public string education { get; set; }
        public string ClassID { get; set; }
        public int courseID { get; set; }
        private bool isChecked;

        public event PropertyChangedEventHandler PropertyChanged;

        public bool IsChecked
        {
            get { return isChecked; }
            set
            {
                if(isChecked!=value)
                {
                    isChecked = value;
                    NotifyOnPropertyChange("IsChecked");
                }
            }
        }
      

      
        protected void NotifyOnPropertyChange(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public virtual RegisterTeacher RegisterTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<RegisterTeacher> RegisterTeachers { get; set; }
    }
}
