//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastAndFinalVersion.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class RegisterTeacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterTeacher()
        {
            this.Courses = new ObservableCollection<Cours>();
        }
    
        public int SNTeacher { get; set; }
        public string UserName { get; set; }
        public int pwd { get; set; }
        public string fullName { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> courseID { get; set; }
        public string education { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Cours> Courses { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
