//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastAndFinalVersion.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class RegisterStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterStudent()
        {
            this.AttendanceLists = new ObservableCollection<AttendanceList>();
        }
    
        public int SN { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public int sNr { get; set; }
        public int semester { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<AttendanceList> AttendanceLists { get; set; }
        public virtual AttendanceList AttendanceList { get; set; }
    }
}
