//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastAndFinalVersion.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseStudentsEntitiesLastStand : DbContext
    {
        public DatabaseStudentsEntitiesLastStand()
            : base("name=DatabaseStudentsEntitiesLastStand")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceList> AttendanceLists { get; set; }
        public virtual DbSet<ChildCourse> ChildCourses { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<RegisterStudent> RegisterStudents { get; set; }
        public virtual DbSet<RegisterTeacher> RegisterTeachers { get; set; }
    }
}
